// tuipr — HUNK: the WHOLE hunk integration (the hunk 0.17.0 CLI contract).
//
// What lives here: the attestation review body and attribution parsing, the
// session probe / wait / reload, comment reading with the MEASURED (b) schema,
// the "no active session" SEPARATE error class, opening the review view (the
// wf26 TTY-fd pattern!), reinjecting findings, and the GitHub upload.
//
// WHY ONE MODULE, despite the size: everything revolves around ONE external
// contract (the `hunk` CLI). The flags, the JSON schemas, and the error classes
// move together when hunk changes version — split apart, the contract would
// live in two places.
//
// LAYER ORDERING: imports downward (proc: spawn diagnostics). Imports NOTHING
// from core or above it.
//
// THE TTY-HANDOFF PATTERN (wf31/19, MEASURED ON THREE LIVE HANGS): the hunk
// view runs in its OWN PSEUDOTERMINAL (`script -q /dev/null`), so there's no
// shared TTY descriptor and no shared process group with the TUI. The earlier
// patterns (a dedicated /dev/tty fd for the child — wf26; `stdin.pause()`
// before the spawn — wf31/18) were NOT enough: the kernel decides TTY reading
// based on the PROCESS GROUP, not the fd. The reasoning is at the head of
// `reviewCommand` and `reviewSpawnOptions`.
import { CORE_ROOT, spawnFailure } from './proc.mjs'
import { spawn, spawnSync } from 'node:child_process'
import { accessSync, chmodSync, constants, statSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import process from 'node:process'
import tty from 'node:tty'

// --- A findings-review body-ja --------------------------------------------

/**
 * The attestation/attribution body for ONE GitHub review (event=COMMENT).
 *
 * The intent: the review was produced locally, and the running USER verified
 * the findings. The model/tool metadata is machine-extractable
 * (parseAttribution) — inside a collapsible <details> block, so it doesn't
 * distract the PR reader.
 *
 * TWO PATHS, ONE BODY. The `tool` field carries the real provenance:
 *   - `hunk` (default): the developer wrote the findings themselves in the
 *     hunk session,
 *   - `claude-p`: the findings were generated by the `claude -p` AI review,
 *     and the developer filtered/edited them in the hunk session.
 * The PROSE follows the tool too: it used to fixedly say "made with hunk",
 * which would be a LIE for an AI review — and provenance is exactly why this
 * block exists.
 *
 * On the AI path the metadata is MEASURED, not declared: `model` comes from
 * the claude wrapper's `modelUsage` key, `costUsd` from `total_cost_usd`.
 * `findings` is ALWAYS the RETAINED (uploaded) count; `aiGenerated` is the raw
 * generated count — the difference between the two IS the human-gate metric.
 */
/**
 * THE HUNK BINARY'S PATH — FROM CORE'S OWN DEPENDENCY, not from the machine.
 *
 * WHY: `hunkdiff` is a tuipr `dependencies` entry, so the TUI BRINGS the tool
 * WITH IT — it doesn't need to be provisioned on the developer's machine
 * (neither brew nor npm -g). This function implements that binding: it
 * returns the bundled binary if it's there.
 *
 * We derive it from `CORE_ROOT`, NOT from cwd — same reasoning as in
 * `CORE_ROOT`'s docstring: the user runs the TUI from a DIFFERENT repo
 * checkout (mobile/web), where core is symlinked or an npm dependency. The
 * `node_modules/.bin` under cwd would therefore belong to the CONSUMER
 * package, where hunkdiff isn't present — the one under `CORE_ROOT`, though,
 * is always OURS.
 *
 * THE PATH FALLBACK IS DELIBERATE, and not error-swallowing: whoever installs
 * hunk for themselves (brew, npm -g, however), for them the bare `'hunk'` name
 * resolves on PATH — the old behavior is preserved byte-for-byte. And
 * `spawnFailure`'s ENOENT diagnosis still speaks up loudly if NEITHER is
 * there.
 *
 * MEMOIZED: within one TUI run the filesystem state doesn't change, but the
 * `d`/`r` path calls this many times. The cache-clearer is for the tests.
 */
let hunkBinCache
export function resetHunkBinCache() {
  hunkBinCache = undefined
}
export function hunkBin() {
  if (hunkBinCache !== undefined) return hunkBinCache
  const local = path.join(CORE_ROOT, 'node_modules', '.bin', 'hunk')
  try {
    // X_OK: mere existence isn't enough, it also has to be executable (the
    // `claudePath` uses the same yardstick).
    accessSync(local, constants.X_OK)
    hunkBinCache = local
  } catch {
    // No bundled instance (e.g. `pnpm install --prod=false`-less install, or
    // a corrupted node_modules) — we fall back to PATH.
    hunkBinCache = 'hunk'
  }
  return hunkBinCache
}

/**
 * The binary's path in a form EMBEDDABLE IN BASH (for the `script`-based PTY
 * wrapping). The absolute path can also contain spaces (e.g. a checkout under
 * "Application Support"), and there an unquoted insertion would split into
 * TWO arguments. The PATH fallback (`'hunk'`) resolves from PATH even when
 * quoted — bash semantics.
 */
export function hunkBinShell() {
  return `'${hunkBin().replaceAll("'", `'\\''`)}'`
}

export function reviewBody({ model, user, count, tool = 'hunk', aiGenerated, costUsd, sessionId, skill, aiSummary }) {
  const lead = tool === 'hunk'
    ? `Review made locally with \`hunk\` — AI-assisted analysis, findings verified by @${user}.`
    : `Review generated locally with \`claude -p\` — verified and filtered by @${user}`
      + (aiGenerated === undefined ? '' : ` (${count}/${aiGenerated} findings kept)`)
      + '.'
  const meta = { tool, model, verifiedBy: user, findings: count }
  // Only ACTUALLY measured fields go in — a `null` spend or a made-up 0 is
  // worse than the field being absent.
  if (skill !== undefined) meta.skill = skill
  if (aiGenerated !== undefined) meta.aiGenerated = aiGenerated
  if (costUsd !== undefined) meta.costUsd = costUsd
  if (sessionId !== undefined) meta.sessionId = sessionId
  // (wf24/2) THE AI SUMMARY GOES IN THE BODY TOO. The agent's verdict (what it
  // reviewed, what the main risk is) is just as useful to the PR reader as it
  // is in the TUI — and until now it appeared NOWHERE. It's included ONLY
  // when it's ACTUALLY there: an empty section is worse than its absence. The
  // `hunk` (non-AI) path stays byte-for-byte unchanged.
  const summaryBlock = typeof aiSummary === 'string' && aiSummary.trim() !== ''
    ? ['', '**AI summary:**', '', aiSummary.trim()]
    : []
  // (wf31/13) THE "This is **not** an approve: … a separate gesture."
  // SENTENCE REMOVED — the user's request, verbatim: "That not-approve
  // sentence is a silly bit of spoon-feeding, take it out."
  //
  // WHY WE LOSE NOTHING BY IT: the review's `event` is `COMMENT`, and GitHub
  // ITSELF signals the state in the review header ("commented" — not
  // "approved", not "requested changes"), without a green check or an
  // approval counter. So the sentence was explaining a fact the platform's UI
  // already states, and more strongly at that (machine state vs. a prose
  // claim). And it's not even our internal gesture-typology that concerns the
  // PR reader anyway.
  //
  // THE COUNT STAYS: `N inline comments` is real information (how much there
  // is to read through), and thanks to `comments[]`'s atomicity it's also a
  // verifiable fact.
  return [
    lead,
    ...summaryBlock,
    '',
    `${count} inline comments.`,
    '',
    '<details>',
    '<summary>Tool and model metadata</summary>',
    '',
    '```json',
    JSON.stringify(meta, null, 2),
    '```',
    '</details>',
  ].join('\n')
}

/** Reading back the reviewBody's metadata block (machine-extractability). */
export function parseAttribution(body) {
  const m = body.match(/```json\n([\s\S]*?)\n```/)
  if (!m) return null
  const meta = JSON.parse(m[1])
  return { tool: meta.tool, model: meta.model, user: meta.verifiedBy, findings: meta.findings }
}

// --- hunk session comments → GitHub review comments[] ----------------------

/**
 * Mapping findings onto the GitHub review `comments[]` shape.
 *
 * IT ACCEPTS TWO INPUT POSITION SCHEMAS, and this is NOT a convenience
 * concession — BOTH are ALIVE in the codebase, side by side:
 *
 *   (A) `{ side: 'new'|'old', line: N }` — the HUNK path's shape
 *       (`parseHunkAgentComments`: computes it from `newRange`/`oldRange`).
 *   (B) `{ newLine: N }` / `{ oldLine: N }` — the ANSWER path's shape
 *       (`hunk-findings.mjs`: the agent's response JSON uses this schema, and
 *       the review store persists it THIS way too; `aiReviewPanelLines`
 *       branches on this as well).
 *
 * A MEASURED, LIVE BUG (the user's #904 case, HTTP 422): this function only
 * knew the (A) schema. On a (B)-shaped finding, `c.line` was `undefined`, so
 * it fell onto the file-level branch — BUT GitHub didn't accept a
 * `subject_type: "file"` comment on this path, and because of `comments[]`'s
 * ATOMICITY the WHOLE review failed. The findings HAD a position (`newLine:
 * 143` and `149`), just under a DIFFERENT field name — the silent shape
 * mismatch thus turned into a 422.
 *
 * WHY WE NORMALIZE HERE, AND NOT IN THE CALLER: this is the SHARED consumer —
 * both the hunk path and the answer path (the cached review's fallback) run
 * into it here. Converting at the call sites, the next new path would fall
 * behind again and produce the same 422.
 *
 * The coordinate space MATCHES: the post-image file line number (hunk
 * `side:"new"` / `line`, or `newLine`) is exactly GitHub's `side:"RIGHT"` /
 * `line` semantics (verified empirically, see the recon report).
 *
 * WARNING: `comments[]` is ATOMIC — a single `line` that isn't in the PR's
 * diff fails the WHOLE review with a 422.
 */
export function toGithubComments(comments) {
  return comments.map((c) => {
    const body = c.rationale ? `${c.summary}\n\n${c.rationale}` : c.summary
    const pos = findingPosition(c)
    // WITHOUT A POSITION, a file-level comment (`subject_type:"file"`) —
    // with `line` it would be a 422. This is the LAST RESORT: the callers
    // (parseHunkAgentComments, normalizeAnswerFindings) already LOUDLY reject
    // a missing position, so in practice a finding only reaches here if some
    // future path skips those gates.
    if (pos === null) {
      return { path: c.filePath, subject_type: 'file', body }
    }
    return {
      path: c.filePath,
      line: pos.line,
      side: pos.side === 'old' ? 'LEFT' : 'RIGHT',
      body,
    }
  })
}

/**
 * A finding's position from WHICHEVER of the TWO accepted schemas: `{ side,
 * line }` or `null`.
 *
 * THE ORDER IS FIXED, and repeats `hunk-findings.mjs`'s doctrine: if BOTH
 * sides are given (an agent slip), the POST-IMAGE (`new`) wins — that's the
 * diff's right side, the one the reviewer reads.
 *
 * FAIL-CLOSED ON A NON-NUMBER POSITION: past the `Number.isInteger` gate,
 * only a real line number can go out. A `"143"` string or `NaN` would give a
 * 422 on GitHub, but here it becomes `null` instead, so the finding STILL
 * goes up as a file-level comment — partial loss of precision instead of a
 * silent full-review failure.
 */
function findingPosition(c) {
  // (A) schema: explicit `side` + `line`.
  if (Number.isInteger(c?.line) && c.line > 0) {
    return { side: c.side === 'old' ? 'old' : 'new', line: c.line }
  }
  // (B) schema: `newLine` / `oldLine`. The post-image comes FIRST (see above).
  if (Number.isInteger(c?.newLine) && c.newLine > 0) return { side: 'new', line: c.newLine }
  if (Number.isInteger(c?.oldLine) && c.oldLine > 0) return { side: 'old', line: c.oldLine }
  return null
}

// --- Data source / action execution ---------------------------------------
//
// From here on these aren't pure functions: fetching the queue and executing
// the actions. The TUI calls these; the tests cover the pure part above.
//
// The process-helper base layer (spawnFailure / fetchRepoRoot / spawnCollect)
// and the path constants (SCRIPT_DIR / NEXT_SH) live in bin/next/proc.mjs.

/**
 * The argv for querying SESSION EXISTENCE.
 *
 * `session list --json` is the SEMANTICALLY correct question: "which active
 * sessions are there?". That's a DIFFERENT question from `comment list`
 * ("what are the findings?") — and separating the two is LOAD-BEARING:
 *
 *   - the session PROBE is the PRECONDITION for starting claude (order
 *     guarantee),
 *   - `comment list` is the `before`/`after` MEASUREMENT.
 *
 * A MEASURED CONSEQUENCE (caught by mutation testing): as long as the probe
 * also ran on `comment list`, the two steps merged UNOBSERVABLY — the order
 * guarantee could be removed without any test going red, because throwing the
 * `before` measurement MASKED the missing wait.
 *
 * NO `--repo` FLAG (MEASURED, hunk 0.17.0):
 *   $ hunk session list --repo /x  →  "error: unknown option '--repo'", exit 1
 * The options are: `--json` and `-h`. So WE do the repo filtering on the
 * JSON — assuming a `--repo` flag here would have given a SILENT exit-1,
 * which the three-state detection (empty stdout + non-zero exit) read as "no
 * session": the TUI would open a new one on every probe.
 */
export function hunkSessionListCommand() {
  return ['session', 'list', '--json']
}

/**
 * Is there an ACTIVE hunk session FOR THIS REPO? — THREE STATES (see
 * `hunkSessionAlive`).
 *
 * SIDE-EFFECT-FREE: `session list` only ASKS (a `reload` would MODIFY, a
 * `diff` would OPEN A NEW ONE — a state query must not do that).
 *
 * THE FILTER GOES ON MATCHING `repoRoot`, because `session list` lists EVERY
 * session — including ones opened for other repos. An unfiltered "there's at
 * least one session" answer would reproduce exactly the user-reported bug:
 * for them the ONE registered session pointed at an ALREADY DELETED temp
 * directory (`/private/var/…/tmp.G4I6zLIvk5/probe`), and there was none for
 * the mobile repo — an unfiltered probe would still have reported an "active
 * session".
 *
 * THE MEASURED JSON SCHEMA (hunk 0.17.0): `{ sessions: [{ sessionId, pid,
 * cwd, repoRoot, … }] }`. `repoRoot` is the anchor, NOT `cwd`: `cwd` is where
 * it was launched from (can also be a subdirectory within the repo), whereas
 * `repoRoot` is the same root that `comment list --repo` expects.
 */
export function probeHunkSession(repoRoot) {
  const res = spawnSync(hunkBin(), hunkSessionListCommand(), { encoding: 'utf8' })
  // A MISSING BINARY / spawn error is NOT a session state (see hunkSessionAlive).
  if (res.error) return null
  if (res.status !== 0) return hunkSessionAlive(res)
  let env
  try {
    env = JSON.parse(res.stdout || '')
  } catch {
    // THE CONTRACT FAILED: from unparseable output we infer NEITHER existence
    // NOR absence. The `null` gives the caller the raw error — a "no session"
    // guess here would open a new hunk on every probe.
    return null
  }
  if (!env || !Array.isArray(env.sessions)) return null
  // THE COMPARISON runs on the RAW roots. hunk gives the realpath'd form
  // (`/private/var/…`), and the caller also uses `git rev-parse
  // --show-toplevel`'s realpath'd root: so the two forms match.
  return env.sessions.some((s) => s?.repoRoot === repoRoot)
}

/**
 * The IDENTIFIER of the repo root's ACTIVE hunk session — the load-guard's
 * anchor.
 *
 * WHY IT'S NEEDED (the user's 5th run, 3rd finding): the `applied` flag on
 * its own is only tied to the PR, but hunk's `q` also TAKES THE SESSION WITH
 * IT — reopening gets a NEW, EMPTY session, where the loaded notes AREN'T
 * there. So the guard has to know WHERE the load happened: `sessionId` is
 * part of the MEASURED schema (`session list --json` →
 * `sessions[].sessionId`, hunk 0.17.0).
 *
 * `null` on EVERY non-measurable branch (error / garbage output / no match):
 * the caller (answerFindingsNeedApply) makes a fail-safe decision from that —
 * `null` never matches an active identifier, so it behaves as "no
 * identifiable active session". It does NOT throw: identifier reading is a
 * cosmetic path alongside the opening, a throw here would take down the
 * whole opening.
 */
export function hunkLiveSessionId(repoRoot) {
  const res = spawnSync(hunkBin(), hunkSessionListCommand(), { encoding: 'utf8' })
  if (res.error || res.status !== 0) return null
  let env
  try {
    env = JSON.parse(res.stdout || '')
  } catch {
    return null
  }
  if (!env || !Array.isArray(env.sessions)) return null
  const own = env.sessions.find((s) => s?.repoRoot === repoRoot)
  const sid = own?.sessionId
  return typeof sid === 'string' && sid !== '' ? sid : null
}

/**
 * THE BACKGROUND REVIEW'S ORDER GUARANTEE: waiting until the session APPEARS.
 *
 * WHY IT'S NEEDED (a requirement of the parallel model (i)): `claude` can
 * ONLY start once the session ALREADY exists — otherwise exactly the same
 * "no active session" error comes back, just IN THE BACKGROUND, and the
 * token is ALREADY spent for nothing. `hunk diff`, though, starts an
 * INTERACTIVE TUI in a SEPARATE process: the session isn't created at the
 * moment of spawn, but when hunk's daemon registers it. This has to be
 * MEASURED, not assumed.
 *
 * THE WAIT polls with EXPONENTIAL BACKOFF (50 → 100 → 200 → … ms), and GIVES
 * UP after `timeoutMs`. The giveup is LOUD: it returns `false`, and the
 * caller does NOT start claude. Silently proceeding here would spend a token
 * on a session that doesn't exist.
 *
 * `sleep` and `now` are INJECTABLE: without that the timeout branch's test
 * would take real seconds (or — worse — be flaky).
 */
export async function waitForHunkSession(repoRoot, {
  timeoutMs = 10_000,
  probe = probeHunkSession,
  sleep = (ms) => new Promise((r) => setTimeout(r, ms)),
  now = () => Date.now(),
} = {}) {
  const started = now()
  let delay = 50
  for (;;) {
    const alive = probe(repoRoot)
    // `true` — got it. `null` — NOT KNOWABLE (daemon error / missing binary):
    // waiting here has NO point, the error isn't about timing. The caller
    // gives the raw diagnosis instead of waiting 10 seconds for an
    // installation error.
    if (alive === true) return true
    if (alive === null) return null
    if (now() - started >= timeoutMs) return false
    await sleep(delay)
    delay = Math.min(delay * 2, 1000)
  }
}

/**
 * The `noteId` SET OF THE AGENT FINDINGS IN THE SESSION.
 *
 * WHY A SET AND NOT A COUNT (a requirement of the parallel model (ii)): in
 * the synchronous model, a `before`/`after` COUNT was enough, because while
 * claude ran NOBODY ELSE could write to the session. In the parallel model
 * the USER ALSO writes — they sit in the diff while the agent works. A mere
 * increment therefore does NOT prove that the AGENT wrote anything: with two
 * user comments the gate would still claim "successful review" even if
 * claude wrote not a single line.
 *
 * THE SET DIFF stays CORRECT even with user writes: it gives exactly the IDs
 * that appeared WHILE claude was running.
 *
 * A MEASURED FACT (hunk 0.17.0, in a live TUI, driven from tmux — the
 * separation is RELIABLE, so the `--type agent` filter alone would already be
 * fine; the set diff is the SECOND line of defense):
 *   - a comment written BY HAND (`c`) in the hunk TUI: `source: "user"`,
 *     `noteId: "user:<epoch-ms>"` — `--type agent` gives an EMPTY list for
 *     this;
 *   - one written via the CLI (`comment apply`): `source: "agent"`,
 *     `noteId: "mcp:<uuid>:<n>"` — `--type user` gives an empty list for this.
 * So the two never blur together; but the set diff stays correct even if a
 * future hunk version changes this.
 */
export function hunkAgentNoteIds(repoRoot, opts) {
  return new Set(hunkComments(repoRoot, opts).map((c) => c.noteId).filter((id) => id !== undefined))
}

/**
 * SWITCHING the EXISTING session to the PR's diff — the core of the
 * SINGLETON behavior.
 *
 * Returns `true` if the reload SUCCEEDED (so NO new session needs opening).
 * `false` if there's nothing to reload (no active / an ORPHANED session) —
 * the caller OPENS one in that case. This fail-soft branch is DELIBERATE:
 * the user ran into exactly the orphaned-session case (a deleted temp root),
 * and throwing there would have been a dead end.
 *
 * THROWS on any OTHER, NAMED hunk error: a false "no session" diagnosis
 * would start a SECOND hunk for the same underlying problem (daemon crash,
 * locked DB).
 */
export function reloadHunkSession(repoRoot, base, head) {
  const res = spawnSync(hunkBin(), hunkSessionReloadCommand(repoRoot, base, head), { encoding: 'utf8' })
  const alive = hunkSessionAlive(res)
  if (alive === true) return true
  if (alive === false) return false
  // `null` — NOT KNOWABLE. A missing binary is a SEPARATE diagnosis (same
  // principle as hunkComments's ENOENT branch): there the problem isn't the
  // session.
  if (res.error?.code === 'ENOENT') {
    throw new Error(
      'the `hunk` binary is not launchable — neither core\'s bundled instance '
      + '(`node_modules/.bin/hunk`, the `hunkdiff` dependency), nor one on PATH. '
      + 'Run `pnpm install` in core. That\'s why the review session can\'t be '
      + 'managed. This is NOT a session error: the binary itself is missing.\n'
      + 'What to do: `brew install hunk` (installs it/puts it on PATH), then try again.',
    )
  }
  const spawnErr = spawnFailure(res, 'hunk')
  if (spawnErr) throw new Error(`the hunk session can't be switched over: ${spawnErr}`)
  throw new Error(
    `switching the hunk session over did not succeed (session reload, exit ${res.status}): `
    + `${(res.stderr || res.stdout || '').trim() || '(no output)'}`,
  )
}




/**
 * Opening the review diff in hunk. Configurable: TUIPR_REVIEW_CMD — the
 * {base}, {head}, {pr} placeholders get substituted.
 *
 * Default: fetching the PR branch into a local ref, then `hunk diff
 * base...head`. This triple-dot form computes from the MERGE BASE, so it
 * gives the same diff that GitHub shows — and hunk's line anchors are the
 * post-image line numbers, which toGithubComments maps directly onto
 * GitHub's RIGHT side.
 */
/**
 * (wf31/19) THE CHILD RUNS IN ITS OWN PTY — via `script(1)`.
 *
 * THE HANG'S ROOT CAUSE, MEASURED ON THREE LIVE INCIDENTS (`ps -o pgid` +
 * `lsof` on the stuck state): hunk and the TUI sat in the SAME process group,
 * and the terminal's foreground pgrp WAS that group — so the KERNEL ALLOWED
 * BOTH to read the TTY. The parent absorbed the keystrokes, hunk sat waiting
 * for input in `S+`, and never got a keypress. From there the chain: it
 * doesn't exit → `close` doesn't fire → `finally` doesn't run → the fds stay
 * open too (the measured stuck state had SIX TTY descriptors on the parent,
 * from repeated `d` openings).
 *
 * THE DECISIVE OBSERVATION: the child HAD its own `/dev/tty` fd (`0r`, the
 * wf26 fix), and STILL got stuck. The kernel decides based on the PGRP, not
 * the fd — so both the fd swap (wf26) and `process.stdin.pause()` (wf31/18)
 * were attacking the WRONG LEVEL. Both were MEASURABLY insufficient: the
 * third hang happened with that fix already in the code.
 *
 * WHAT I ALSO RULED OUT, BY MEASUREMENT: `bash -mc` (job control). In `-m
 * -c` mode it does NOT put things into a separate process group — the
 * child's pgid stays the same as the parent's (measured: 41193 in both
 * forms). The assumption was wrong.
 *
 * `script -q /dev/null`, though, gives the child its OWN PSEUDOTERMINAL, and
 * makes it a process group leader (measured: `pgid == pid`,
 * `tty=/dev/ttysNNN` — DIFFERENT from the parent's terminal). The contention
 * thus disappears IN PRINCIPLE: hunk reads its own PTY, the parent reads its
 * own — no shared descriptor, no shared pgrp.
 *
 * `-q` suppresses `script`'s header/footer ("Script started/done on …"),
 * which would otherwise write into the TUI's picture. `/dev/null` is the
 * typical scriptfile stand-in: `script` ALWAYS logs, but we throw it away
 * here.
 *
 * PASSING THE TERMINAL SIZE IS A REQUIREMENT, NOT A NICETY: `script`'s PTY
 * gets a DEFAULT size, not the real terminal's — measured, it even gave `0
 * 0`. At the wrong width the hunk TUI wraps/truncates. So the child's shell
 * FIRST sets the MEASURED size via `stty` (and turns off echo — see there),
 * and only then starts hunk. The size is the value valid AT THE MOMENT OF
 * SPAWN (the caller passes it in) — a resize AFTER the spawn isn't tracked,
 * which is a KNOWN LIMITATION: hunk stays at that same size until `q`. (The
 * user's feedback: "hunk doesn't resize with the terminal window, but that's
 * something we can live with.")
 */
function ptyWrap(inner, { columns, rows }) {
  // THE SIZE PREFIX ONLY GOES IN WITH A MEASURED VALUE: a made-up `80 24`
  // would be worse than `script`'s default, because it gives FALSE precision.
  // On a non-TTY (pipe, test) the caller gives `null`, and then the `stty`
  // is left out too.
  //
  // (wf31/20) `-echo` GOES IN TOO: `script`'s PTY starts with DEFAULT ECHO,
  // and on opening writes a `^D\b\b` to the output (MEASURED: `od -c` on
  // `script -q`'s output — `-q` suppresses the header, but NOT THIS). This
  // litters the TUI's picture/the scrollback. hunk sets its own raw mode
  // anyway, so turning off echo doesn't affect its behavior — it only
  // cleans up the PTY's starting state.
  const sttyArgs = ['-echo']
  if (Number.isInteger(columns) && columns > 0 && Number.isInteger(rows) && rows > 0) {
    sttyArgs.push(`rows ${rows}`, `cols ${columns}`)
  }
  // `exec` IS LOAD-BEARING: without it the shell would STAY ALIVE alongside
  // hunk, so `script`'s child would be a shell, not hunk — and the `close`
  // event would fire when the SHELL (not hunk) exits. `exec` also removes
  // one process from the chain.
  return ['script', ['-q', '/dev/null', 'bash', '-c', `stty ${sttyArgs.join(' ')}; exec ${inner}`]]
}

/**
 * The hunk-diff command's INNER (writable into `bash -c`) form, WITHOUT the
 * `script` wrapper.
 *
 * WHY IT'S SPLIT OUT from `ptyWrap`: the node-pty relay (`openReviewViaPty`,
 * below) ITSELF gives the child its own PTY and its own process group — the
 * `script`-based wrapper (which exists for EXACTLY these two properties, see
 * `ptyWrap`'s header) would be REDUNDANT there. But building the command is
 * IDENTICAL on BOTH paths (the `TUIPR_REVIEW_CMD` template + the default
 * `hunk diff`), so it lives in ONE place — split apart, the template
 * substitution would easily fall behind on one path at some future change.
 */
export function reviewInnerCommand(pr, base, head, { agentNotes = false } = {}) {
  const tpl = process.env.TUIPR_REVIEW_CMD
  if (tpl) {
    // THE TEMPLATE is the user's OWN command — we don't inject a flag into
    // it: they know what they want to run, and a foreign `--agent-notes`
    // could well trip it up.
    return tpl.replaceAll('{pr}', String(pr)).replaceAll('{base}', base).replaceAll('{head}', head)
  }
  // `--agent-notes` is a MEASURED flag (hunk 0.17.0 `diff --help`: "show
  // agent notes by default"): on opening the review (r, and the `d` load
  // path too) the AI comments are IMMEDIATELY visible, no need for the `a`
  // toggle. The pending-free `d` path runs WITHOUT the flag — staying,
  // byte-for-byte, hunk's default.
  return `${hunkBinShell()} diff${agentNotes ? ' --agent-notes' : ''} "${base}...${head}"`
}

export function reviewCommand(pr, base, head, { agentNotes = false, columns = null, rows = null } = {}) {
  // THE PTY WRAPPING IS NEEDED HERE: the hang comes from TTY contention,
  // which is INDEPENDENT of what we run — the user's own template
  // (`TUIPR_REVIEW_CMD`) would get stuck the same way. This path is for the
  // `script`-based (non-node-pty) opening, see `openReviewView`'s call site.
  return ptyWrap(reviewInnerCommand(pr, base, head, { agentNotes }), { columns, rows })
}

/**
 * THE hunk-diff SPAWN OPTIONS — `cwd` gets decided HERE, in ONE place.
 *
 * ROOT CAUSE OF A REAL, USER-REPORTED BUG ("no active session" even after
 * `d`): `openReview` used the `spawnSync(cmd, args, { stdio: 'inherit' })`
 * form **WITHOUT `cwd`**. So hunk saw the TUI PROCESS's working directory as
 * repoRoot, while `hunkComments` queried the `--repo <git rev-parse
 * --show-toplevel>` root. So the session was created against a DIFFERENT
 * root than the one we were looking for — and the two roots only matched
 * when the user happened to launch the TUI from the repo's root.
 *
 * MEASURED ON A TMUX PTY (the TUI launched from a directory OUTSIDE the
 * repo):
 *   hunk diff origin/main...refs/tuipr/pr/101   [cwd=/tmp/tuipr-pty/elsewhere]
 *   hunk session comment list --repo /tmp/tuipr-pty/repo --type agent --json
 *
 * FAIL-SOFT, BUT NOT DISHONEST: if the root isn't measurable (empty/null),
 * `cwd` is LEFT OUT — the process inherits its own, as before. A `cwd: ''`
 * on spawnSync would give DIFFERENT behavior (and `d` would silently fail),
 * while a `cwd: undefined` would suggest false precision at the call site.
 *
 * --- (wf26) STDIO: WHY IT'S NO LONGER `'inherit'` --------------------------
 *
 * A FINDING FROM THE USER'S 6TH LIVE RUN: exiting the hunk view with `q`, the
 * TUI DID NOT COME BACK — the list disappeared, only the header line
 * remained in the shell. The process neither crashed nor exited: it FROZE
 * FOREVER.
 *
 * THE DIAGNOSIS, on a live PTY, measuring the FROZEN process with
 * `sample(1)` — the main thread's native stack at the moment of the hang:
 *
 *   uv_run → uv__io_poll → uv__stream_io → read (libsystem_kernel.dylib)
 *
 * So the loop sits in a BLOCKING `read()` on the TTY (NOT in `kevent`), so it
 * CAN'T EVEN PROCESS the SIGCHLD signaling the child's death: hunk's child
 * turned into a ZOMBIE (`ps`: `ZN+ <defunct>`), `openReviewView`'s promise
 * never settled, and even the `setInterval` timers stopped. So the `d` path
 * NEVER EVEN REACHED the render after resume — the bug is NOT the render,
 * NOT the `loadedAt`-based hiding, and NOT the wf20 async reload.
 *
 * THE CAUSE is `stdio: 'inherit'`: the child got the SAME TTY fd that Node
 * (through Ink's raw-mode stdin) was ALREADY reading from.
 *
 * THE MEASURED ISOLATION (reproduced on a live PTY, without Ink too):
 *   - without stdin reading / only `setRawMode` / only `ref()` → `close` FIRES
 *   - a `readable` listener OR `resume()`                      → HANGS
 *   - `pause()` + `unref()` + `removeAllListeners()` before spawn → HANGS
 *     (the blocking `read()` is ALREADY inside the syscall — not revocable
 *     at the stream level; that's why "pausing" around the call site is NOT
 *     the fix)
 *   - a dedicated `/dev/tty` fd for the child                  → `close` FIRES
 *
 * THE CHILD'S INTERACTIVITY IS NOT AFFECTED (measured in the child on a live
 * PTY: `tty=/dev/tty`, `[ -t 0 ]` = yes, `stty size` = 30 120, keypresses
 * arrive, `q` exits), and the parent RECLAIMS the terminal after closing: the
 * `/dev/tty` is the SAME terminal, just a DIFFERENT fd — that's exactly what
 * resolves the stuck state.
 *
 * `closeFds()` is NOT an optional nicety: `d` runs many times within one
 * session, and with an fd leak the TUI would sooner or later die with EMFILE.
 */
export function reviewSpawnOptions(repoRoot) {
  const root = typeof repoRoot === 'string' ? repoRoot.trim() : ''
  const base = root === '' ? {} : { cwd: root }
  return {
    ...base,
    // (wf31/19) ALL THREE DIRECTIONS `'inherit'` — the dedicated `/dev/tty`
    // fd REMOVED.
    //
    // WHY: the child now runs in its OWN PTY (`script -q /dev/null` — see
    // `reviewCommand`'s header), so its terminal is provided by `script`, not
    // us. A separate `/dev/tty` opening in this model is REDUNDANT (the
    // contention has already been eliminated at the PTY level) and also
    // HARMFUL: `script` wants to bind ITS OWN PTY to the child's stdin, and an
    // explicit fd would override that.
    //
    // WHAT GOES AWAY WITH IT: the fd LEAK. In the measured, stuck state the
    // parent had SIX TTY descriptors (`0u 1u 2u 11u 15u 16u 17r`) —
    // `closeFds()` only ran if the promise settled, and with a hang it
    // didn't. What we don't open, we don't need to close either.
    //
    // WHAT STAYS UNCHANGED: the `[fd, fd, fd]` form CRASHED on Bun's `kqueue`
    // (EINVAL, measured on hunk 0.17.0 / Bun v1.3.14) — that's why we didn't
    // go back to explicit write fds either. `'inherit'` is the measured,
    // working form.
    stdio: 'inherit',
    // `closeFds` STAYS a NO-OP: the call site's `finally` calls it
    // (`spawnOpts.closeFds?.()`), and its contract (idempotent, never throws)
    // is unchanged — there's just nothing left to close.
    closeFds: () => {},
  }
}

// (wf31/19) `defaultOpenTty` REMOVED: the child runs in its own PTY
// (`script -q /dev/null`), so we don't open a `/dev/tty` for it. The
// reasoning is in `reviewSpawnOptions`'s stdio explanation.

/**
 * Opening the hunk-diff view as an ASYNCHRONOUS child — handing over the
 * terminal.
 *
 * WHY NOT `spawnSync` (A MEASURED BUG, observed on a live PTY in tmux):
 * `spawnSync` blocks the NODE EVENT LOOP for the child's WHOLE lifetime. And
 * the hunk TUI runs until the user presses `q` — so with spawnSync,
 * PARALLELISM IS IMPOSSIBLE IN PRINCIPLE: `waitForHunkSession`'s poll NEVER
 * ran again, and `claude` only started AFTER the diff CLOSED. The log showed
 * this: the session was ALREADY alive (`session.alive` existed), yet the wait
 * made no progress, because the loop was stuck.
 *
 * With `spawn` the loop stays free: the session probe runs, claude starts,
 * and the findings appear in the diff that's STILL OPEN — exactly what the
 * user asked for.
 *
 * `stdio: 'inherit'` is UNCHANGED: hunk needs a REAL TTY (interactive TUI).
 * The promise settles when the child EXITS, so the caller can still wait for
 * the view to close — it just doesn't freeze the process meanwhile.
 */
export function openReviewView(cmd, args, opts, {
  spawn: spawnImpl = spawn,
  watchdog = null,
  onExit = null,
} = {}) {
  return new Promise((resolve, reject) => {
    const child = spawnImpl(cmd, args, opts)
    let settled = false
    // `stopWatch`'s DECLARATION BEFORE `done` — `done` reads it through its
    // closure, and a `let` below it would give a TDZ error if `close` fired
    // BEFORE the watchdog was set up (short-lived child: ENOENT, immediate
    // exit).
    let stopWatch = null
    const done = (fn, arg) => {
      if (settled) return
      settled = true
      stopWatch?.()
      fn(arg)
    }
    // (wf31/16) THE STUCK-STATE WATCHDOG — from a live user incident.
    //
    // THE SYMPTOM: `d` opened `hunk diff`, and the WHOLE terminal froze — no
    // mouse, no keyboard, no `Ctrl-C`. The measured state (`ps`/`lsof`): hunk
    // was `S+` (foreground, WAITING FOR INPUT), and held TWO reader fds on
    // the same `/dev/tty`, while the parent Node's libuv was also stuck
    // inside a blocking TTY `read()`. `Ctrl-C` had no effect either: Ink's
    // raw mode turns off `ISIG`, so `^C` turned into a BYTE instead of a
    // signal — going to a reader that didn't process it.
    //
    // WHY "DOES IT WRITE ANYTHING" ISN'T THE SIGNAL: the child's
    // stdout/stderr are INHERITED (`stdio: [fd, 'inherit', 'inherit']` — see
    // `reviewSpawnOptions`'s reasoning), so the parent CANNOT SEE what it
    // writes. Detecting a "gone silent" child is impossible in principle on
    // this path.
    //
    // THE RELIABLE SIGNAL IS THE SESSION APPEARING, measured from ANOTHER
    // process: `hunk session list --json` asks the DAEMON (not the child
    // sitting on the TTY), so it answers even if the child is stuck on the
    // terminal. If hunk starts NORMALLY, the session registers within
    // seconds; if it's stuck on the TTY, NEVER. This is `waitForHunkSession`'s
    // already-proven mechanism — here we just use it for a DIFFERENT purpose
    // (a guard, not an order guarantee).
    //
    // FAIL-SOFT ON EVERY UNCERTAINTY: `watchdog` ONLY kills if the probe gave
    // an EXPLICIT `false` (the daemon answered, and the session ISN'T there).
    // `null` (not measurable: daemon error, missing binary) is NOT a kill —
    // there we don't know what's happening, and cutting off a WORKING diff is
    // worse than waiting. The same doctrine that governs `probeHunkSession`'s
    // `null` branch.
    if (watchdog) stopWatch = watchdog(child, (reason) => done(reject, reason))
    child.on('error', (error) => {
      done(reject, error?.code === 'ENOENT'
        ? new Error(
          `\`${cmd}\` is not launchable (ENOENT): it's not installed, or not on PATH. `
          + 'This is NOT a review error — the binary itself is missing.',
        )
        : new Error(`the diff view could not be launched: ${error?.message ?? String(error)}`))
    })
    // A NON-ZERO EXIT IS NOT AN ERROR: exiting the hunk TUI (`q`) is
    // legitimate, and pager-like tools often return non-zero on interruption.
    // `d`'s contract is that the view CLOSED — not that it did so with 0.
    // (wf31/48) THE `exit` HOOK — A SIGNAL EARLIER THAN `close`, FOR COSMETIC
    // PURPOSES.
    //
    // WHY IT'S NEEDED SEPARATELY FROM `close`: the promise resolves ON
    // `close` (that's the correct contract — by then stdio has closed too),
    // BUT `close`, per measurement, comes ~50 ms AFTER the process's actual
    // exit. hunk, though, writes `?1049l` IMMEDIATELY on exit, so in that
    // window the shell's picture shows through. The caller can step back
    // into the alt screen on this hook as early as possible.
    //
    // PURELY COSMETIC: the hook does NOT settle the promise, and its error
    // doesn't change the outcome either — a throwing hook must not be able to
    // take down the `d` path. That's why it's fail-soft, and why it does NOT
    // go through `done`.
    child.on('exit', () => {
      try {
        onExit?.()
      } catch { /* cosmetic hook: its error doesn't affect closing the view */ }
    })
    // A NON-ZERO EXIT IS NOT AN ERROR (see above) — `close` is the settle point.
    child.on('close', () => done(resolve))
  })
}

/**
 * (wf31/16) THE STUCK-STATE WATCHDOG'S FACTORY — fed into
 * `openReviewView({ watchdog })`.
 *
 * THE CONTRACT: returns a `stop()` that `openReviewView` calls on EVERY
 * outcome (success, error, kill) — without that the timer would stay alive
 * for the TUI's whole lifetime.
 *
 * THE THRESHOLD'S REASONING (`graceMs`): `waitForHunkSession`'s default is
 * 10 s for the ORDER GUARANTEE — there the patience is justified, because
 * starting claude is the stake. The WATCHDOG, though, has to catch the HANG,
 * and there the price of patience is the user staring at a dead terminal for
 * that long. 20 s is DOUBLE the proven wait: it's sure to let through a slow
 * (large repo, cold daemon) start, but doesn't leave it frozen for minutes.
 * NOT configurable at the call site — a per-call threshold is exactly the
 * kind of drift the next "why did it cut it off?" finding would come from.
 *
 * `probe` and `sleep`/`now` are INJECTABLE, following `waitForHunkSession`'s
 * pattern: without that the watchdog's test would take real 20 seconds.
 */
export function makeStuckViewWatchdog(repoRoot, {
  graceMs = 20_000,
  probe = probeHunkSession,
  sleep = (ms) => new Promise((r) => setTimeout(r, ms)),
  now = () => Date.now(),
} = {}) {
  return (child, onStuck) => {
    let stopped = false
    const started = now()
    const loop = async () => {
      let delay = 500
      for (;;) {
        await sleep(delay)
        if (stopped) return
        // THE CHILD IS ALREADY GONE: `close` will settle the promise anyway,
        // nothing to do here. (Either `exitCode`/`signalCode` non-null →
        // closed.)
        if (child.exitCode !== null || child.signalCode !== null) return
        const alive = probe(repoRoot)
        // SESSION FOUND → hunk is running NORMALLY, the watchdog STANDS DOWN.
        // From here the view lives as long as the user wants (`q`) — that's
        // the contract.
        if (alive === true) return
        // NOT MEASURABLE (`null`) → we do NOT kill (see the fail-soft
        // reasoning above). Keep polling: maybe the daemon recovers within
        // the grace period.
        if (alive === false && now() - started >= graceMs) {
          stopped = true
          // KILLING THE CHILD: `SIGTERM` FIRST. In the measured incident the
          // stuck hunk EXITED on this, and afterward the parent's `close`
          // handler ran cleanly (the whole chain unwound) — so `SIGKILL`
          // isn't necessary as the first step, and the gentler signal gives
          // hunk a chance to restore the terminal state (raw mode, alternate
          // screen).
          try { child.kill('SIGTERM') } catch { /* already gone */ }
          // `SIGKILL` IS THE BACKSTOP: if `SIGTERM` has no effect either, the
          // hang persists. The `unref` is load-bearing: without it this timer
          // would also delay the TUI's exit.
          const hard = setTimeout(() => {
            try { child.kill('SIGKILL') } catch { /* already gone */ }
          }, 2000)
          hard.unref?.()
          onStuck(new Error(
            'the hunk-diff view got STUCK: the session did not appear within '
            + `${Math.round(graceMs / 1000)} seconds while the hunk `
            + 'process was running — we closed the view so the terminal would '
            + 'not freeze.\n'
            + 'This is the measured error class of TTY handoff (the child and '
            + 'the TUI read the same terminal). What to do: try `d` again; if '
            + 'it recurs, open a session in a separate terminal '
            + '(`hunk diff <base>...<head>`), and the TUI will use that.',
          ))
          return
        }
        delay = Math.min(delay * 2, 2000)
      }
    }
    void loop()
    return () => { stopped = true }
  }
}

// --- node-pty relay: eliminating the SHELL FLASH on the hunk↔TUI switch ----
//
// The `script`-based path (ptyWrap/openReviewView, above) solves the THREE
// LIVE HANGS (own PTY, own process group — see `ptyWrap`'s header), but the
// ~40 ms shell flash MEASURED ON HUNK'S EXIT REMAINS: `script` only closes
// AFTER hunk dies, and in the meantime hunk's `?1049l` goes to the raw,
// inherited fd (`stdio: 'inherit'`) — the parent doesn't see it, can't hold
// it back.
//
// With node-pty, the parent IS the relay itself: the child's ENTIRE byte
// stream goes through `onData`, so the `?1049l` CAN BE FILTERED OUT BEFORE
// it reaches the real terminal — from here on WE conduct the switch, not
// hunk. So the terminal NEVER falls back to the primary buffer on hunk's
// exit: this isn't NARROWING the window, it's ELIMINATING it in principle.
//
// OPTIONAL DEPENDENCY: `node-pty` requires a native build (pnpm
// `allowBuilds` approval + a platform-specific prebuild), which isn't
// available on every machine. The caller has to work REGARDLESS of that —
// see `openReviewViaPty`'s error class.
let nodePtyCache // undefined = not tried yet; null = tried, doesn't work; otherwise the loaded module
export function resetNodePtyCache() {
  nodePtyCache = undefined
}
/**
 * RESTORING the node-pty `spawn-helper`'s EXECUTE PERMISSION — fixing an
 * UPSTREAM PACKAGING BUG AT THE POINT OF USE.
 *
 * WHAT THIS FILE IS: the TENTH argument to `pty.fork()`
 * (`node-pty/lib/unixTerminal.js`), which the native module runs INSTEAD OF
 * the target command. This is what calls `setsid()` and `TIOCSCTTY`, and then
 * `exec`s hunk — in other words, THIS is what gives the child its own session
 * and CONTROLLING TERMINAL. Exactly the property the `script -q /dev/null`
 * wrapper was also built for (see `ptyWrap`'s header), and what eliminated
 * the THREE LIVE HANGS. Not a helper program: it IS the isolation mechanism
 * itself.
 *
 * THE BUG, MEASURED (node-pty 1.1.0):
 *   - in the PUBLISHED npm tarball, the `spawn-helper`'s mode is `-rw-r--r--`
 *     (verified on the registry tarball: `tar -tvzf` → `-rw-r--r-- …
 *     prebuilds/darwin-arm64/spawn-helper`),
 *   - the `install` script (`scripts/prebuild.js`) ONLY CHECKS whether a
 *     prebuild exists — it doesn't build and doesn't chmod,
 *   - `postinstall` (`scripts/post-install.js`) cleans up `build/Release` and
 *     copies conpty on Windows — `chmod` is NOWHERE in it.
 * So the package relies ENTIRELY on tar extraction preserving the exec bit —
 * which the tarball itself doesn't carry. Symptom: `posix_spawnp failed`.
 *
 * WHY ONLY ON MACOS: the package has a prebuild ONLY for `darwin-*` and
 * `win32-*` platforms. There's none on Linux, so `node-gyp rebuild` runs
 * there, the helper is compiled LOCALLY, and ends up executable. This bug
 * does NOT affect Ubuntu CI — it affects macOS dev machines and the macOS
 * runner.
 *
 * WHY HERE, AND NOT IN A POSTINSTALL SCRIPT: core is the ONLY consumer of
 * node-pty, so fixing it in this one place takes effect in EVERY install
 * form (workspace overlay, standalone mobile/web from the vendored
 * snapshot, CI) — without having to touch three repos' install pipelines.
 * It's also SELF-HEALING: it runs again on first use after a `pnpm store
 * prune` or a fresh clone.
 *
 * FAIL-SOFT, DELIBERATELY: if the file isn't there, or the store is
 * read-only, we do NOT throw — the caller's `openReviewViaPty` falls back to
 * the `script`-based path with `NODE_PTY_UNAVAILABLE` regardless. So in the
 * worst case this fix does nothing; it cannot cause harm.
 */
function ensureSpawnHelperExecutable() {
  // No `spawn-helper` on Windows (the conpty/winpty path runs there instead)
  // — nothing to do.
  if (process.platform === 'win32') return
  let root
  try {
    root = path.dirname(createRequire(import.meta.url).resolve('node-pty/package.json'))
  } catch {
    return // not installed — the caller's fallback takes over
  }
  // THE TWO POSSIBLE LOCATIONS: the prebuild (this is the buggy branch) and
  // the locally compiled output (this one is already executable, but the
  // check is cheap and harmless).
  const candidates = [
    path.join(root, 'prebuilds', `${process.platform}-${process.arch}`, 'spawn-helper'),
    path.join(root, 'build', 'Release', 'spawn-helper'),
  ]
  for (const candidate of candidates) {
    let mode
    try {
      mode = statSync(candidate).mode
    } catch {
      continue // no helper on this branch — the other candidate can be next
    }
    try {
      accessSync(candidate, constants.X_OK)
      return // ALREADY executable: nothing to fix
    } catch { /* not executable — this is what we came to fix */ }
    try {
      // We ADD the exec bit to the EXISTING mode (`| 0o111`), not overwrite
      // it: the store's owner set the read/write permissions, we don't touch
      // those.
      chmodSync(candidate, mode | 0o111)
    } catch { /* read-only store — the caller's fallback takes over */ }
    return
  }
}

async function loadNodePty() {
  if (nodePtyCache !== undefined) return nodePtyCache
  // THE FIX RUNS BEFORE LOADING: `spawn-helper` is needed at the moment of
  // SPAWN, but `loadNodePty` is the memoized entry point — so this runs ONCE
  // per round, not on every `d` press.
  ensureSpawnHelperExecutable()
  try {
    nodePtyCache = await import('node-pty')
  } catch {
    // NOT installed, or no native build for this platform — the caller falls
    // back to the `script`-based path (see `openReviewViaPty`), NOT a loud
    // error.
    nodePtyCache = null
  }
  return nodePtyCache
}

/**
 * The caller recognizes the "fall back to the `script`-based path" state
 * (thrown by `openReviewViaPty`) by THIS `.code` — DISTINGUISHED from
 * node-pty being AVAILABLE but the review session collapsing on its own
 * (the LATTER is a real error, and must not be treated as a silent
 * fallback).
 */
export const NODE_PTY_UNAVAILABLE = 'TUIPR_NODE_PTY_UNAVAILABLE'

/**
 * FILTERING OUT hunk's `?1049l` (alt-screen EXIT) sequence from the node-pty
 * byte stream.
 *
 * WHY A STATEFUL SEARCH IS NEEDED AT ALL: node-pty's `onData` gives a STRING
 * (the native layer has already decoded to UTF-8, so multi-byte character
 * boundaries are ALREADY correct — measured: `encoding` defaults to `'utf8'`,
 * node-pty's unixTerminal.js calls `_socket.setEncoding('utf8')`) — but the
 * SEARCHED ESCAPE SEQUENCE can still get split across an `onData` call
 * boundary regardless, because the pty delivers data in arbitrarily sized
 * chunks. `carry` therefore holds the character tail that PARTIALLY matches
 * the PATTERN and is NOT YET DECIDABLE, until the NEXT `feed()` call.
 *
 * WHY IT DOESN'T ALSO FILTER `?1049h`: the intent is EXCLUSIVELY to hold back
 * the EXIT. hunk's own ENTRY (the `?1049h` written at the start of the
 * session) is HARMLESS and PASSES THROUGH unchanged — the terminal is
 * ALREADY in the alt screen at that point (the caller wrote its own
 * `?1049h` BEFORE the spawn, see `openHunkView`'s call site in
 * tui-app.mjs), so hunk's write repeats an escape code that's a no-op from
 * the terminal's perspective, but is still a REAL one — exactly as it does
 * on today's `script`-based path too.
 */
export function createAltScreenExitFilter() {
  const PATTERN = '\u001B[?1049l'
  let carry = ''
  return {
    /** @returns {string|null} the part writable to the output, `null` if none. */
    feed(chunk) {
      const s = carry + String(chunk)
      let out = ''
      let i = 0
      while (i < s.length) {
        let matched = 0
        while (matched < PATTERN.length && i + matched < s.length && s[i + matched] === PATTERN[matched]) {
          matched++
        }
        if (matched === PATTERN.length) {
          // FULL MATCH — this sequence does NOT go to the output.
          i += matched
          continue
        }
        if (i + matched === s.length) {
          // the chunk ENDS HERE, while partially matching the PATTERN — the
          // NEXT feed() call decides, we keep the tail.
          carry = s.slice(i)
          return out.length > 0 ? out : null
        }
        out += s[i]
        i++
      }
      carry = ''
      return out.length > 0 ? out : null
    },
    /**
     * The tail left over at the END of the stream, still NOT DECIDABLE — by this point it
     * was NEVER a full match (`feed()` swallows a full match IMMEDIATELY,
     * without writing it out, before it would ever land in `carry`).
     *
     * DELIBERATELY DISCARDED, NOT WRITTEN OUT: by construction, `carry` can
     * ONLY be a REAL, non-empty PREFIX of `\u001B[?1049l` (in
     * `feed()` it only ends up there if `matched > 0` AND the string happens
     * to end right there — see there). A truncated escape prefix (e.g. a lone
     * `\u001B` or `\u001B[?1049`) written to the terminal would leave an
     * UNCLOSED sequence for the parser — the child can only be cut off like
     * this if it was killed/crashed IN THE MIDDLE, meaning no more bytes will
     * EVER come to close it. The missing couple of bytes (which would have
     * been either `h` or `l`) don't carry meaningful content anyway —
     * discarding here is STRICTER than `feed()`'s doctrine (which keeps
     * EVERY non-matching byte), but only because this tail is, BY
     * DEFINITION, never "normal content".
     */
    flush() {
      carry = ''
      return null
    },
  }
}

/**
 * Opening the hunk-diff view through a node-pty RELAY — INSTEAD of the
 * `script`-based path (`openReviewView`), when node-pty is available.
 *
 * THE MECHANISM: the child runs in its OWN pseudoterminal (node-pty gives it
 * one), so it NEVER reaches our REAL terminal (our fd 0/1/2) — WE relay the
 * byte stream in both directions:
 *   - OUTPUT: `child.onData` → (with `?1049l` filtered out, see
 *     `createAltScreenExitFilter`) → `process.stdout`,
 *   - INPUT: our stdin (our own, dedicated `tty.ReadStream(0)`) →
 *     `child.write`.
 *
 * THE PROCESS-GROUP ISOLATION (the fix for the THREE LIVE HANGS, see
 * `ptyWrap`'s header) STAYS, just with a different tool: node-pty starts the
 * child in its OWN PTY and its OWN process group (MEASURED, with a live
 * test: the child's pgid matches its OWN pid, DIFFERS from the parent's) —
 * so the reasoning behind the `script`-based path (the kernel decides TTY
 * reading based on PGRP, not fd) holds HERE TOO.
 *
 * THE STDIN RELAY uses a SEPARATE `tty.ReadStream(0)`, NOT Ink's
 * `stdinWrapper` target: the caller (`tui-app.mjs`) has already called
 * `stdinWrapper.destroyOldTarget()` BEFORE the spawn (per the
 * `DelegatingStdin` contract), so the old target is ALREADY not reading by
 * then — the relay keeps ITS OWN, FRESH stream open for the child's ENTIRE
 * lifetime, and `destroy()`s it AFTER exit. The caller calls
 * `attachFreshTarget()` AFTER THAT, which creates ANOTHER fresh stream meant
 * for Ink. So the two streams don't overlap IN TIME — the same proven
 * pattern (destroy → [work] → fresh attach) as on the `stdio: 'inherit'`
 * path, just here the "work" is ACTIVE relaying, not idle waiting. There are
 * NEVER two readers on the fd at once, because the child ITSELF never
 * reaches this fd (it lives in its own PTY) — the earlier (pre-wf26) error
 * class (two readers on the SAME inherited fd) can't even come up here.
 *
 * @throws {Error} `.code === NODE_PTY_UNAVAILABLE`, if `import('node-pty')`
 *   throws, OR `pty.spawn()` itself throws (native build missing/broken on
 *   the platform) — the caller recognizes from THIS code that it has to fall
 *   back to the `script`-based path; this is NOT a review error.
 */
export async function openReviewViaPty(command, { cwd = null, columns = null, rows = null } = {}, {
  onExit = null,
  watchdog = null,
} = {}) {
  const nodePty = await loadNodePty()
  if (!nodePty) {
    const err = new Error('`node-pty` isn\'t resolvable — the caller has to fall back to the `script`-based path')
    err.code = NODE_PTY_UNAVAILABLE
    throw err
  }
  // WITH A MEASURED VALUE, IF THERE IS ONE: on a non-TTY (the caller gives
  // `null`) node-pty's default (80x24) is used — we don't write in a made-up
  // size here either, same doctrine as in `ptyWrap`'s header.
  const cols = Number.isInteger(columns) && columns > 0 ? columns : 80
  const rowsN = Number.isInteger(rows) && rows > 0 ? rows : 24
  let child
  try {
    child = nodePty.spawn('bash', ['-c', command], {
      name: 'xterm-256color',
      cols,
      rows: rowsN,
      cwd: cwd || process.cwd(),
      env: process.env,
    })
  } catch (error) {
    // A NATIVE BUILD broken/missing on the platform — the SAME fallback
    // signal as an import error: from the caller's perspective the two
    // causes are indistinguishable ("node-pty just doesn't work right now
    // here"), the reaction (fall back to `script`) is identical.
    const err = new Error(
      `the node-pty spawn didn't succeed — the caller has to fall back to the \`script\`-based path: ${error?.message ?? error}`,
    )
    err.code = NODE_PTY_UNAVAILABLE
    throw err
  }

  return new Promise((resolve, reject) => {
    let settled = false
    let stopWatch = null
    let outputSub = null
    const relayStdin = new tty.ReadStream(0)
    const resizeHandler = () => {
      const c = process.stdout.columns
      const r = process.stdout.rows
      if (Number.isInteger(c) && c > 0 && Number.isInteger(r) && r > 0) {
        try { child.resize(c, r) } catch { /* the child is just closing — the relay must not fail on it */ }
      }
    }

    const cleanupRelay = () => {
      outputSub?.dispose?.()
      process.stdout.removeListener('resize', resizeHandler)
      // FAIL-SOFT: the stream may already be destroyed by this point (e.g. an
      // earlier error branch ran) — a cleanup error must not fail the
      // caller, the goal (no active reader of ours left on the fd) is met
      // regardless.
      try { relayStdin.setRawMode(false) } catch { /* see above */ }
      try { relayStdin.destroy() } catch { /* see above */ }
    }
    const done = (fn, arg) => {
      if (settled) return
      settled = true
      stopWatch?.()
      cleanupRelay()
      fn(arg)
    }

    try {
      // FOR THE STUCK-STATE WATCHDOG, `makeStuckViewWatchdog` can be
      // REUSED UNCHANGED — its contract is `child.exitCode`/
      // `child.signalCode`/`child.kill(sig)`, but `IPty` doesn't HAVE these
      // (only an `onExit` event + `kill(sig)`). The SHIM bridges these TWO
      // surfaces, so the hang-detection CODE doesn't have to be duplicated
      // for two tools.
      const watchdogShim = { exitCode: null, signalCode: null, kill: (sig) => child.kill(sig) }
      if (watchdog) stopWatch = watchdog(watchdogShim, (reason) => done(reject, reason))

      const filter = createAltScreenExitFilter()
      outputSub = child.onData((chunk) => {
        const out = filter.feed(chunk)
        if (out !== null) process.stdout.write(out)
      })

      // THE INPUT RELAY — see the function's header. RAW MODE IS NEEDED:
      // hunk expects character-by-character keypresses, not line-buffered
      // (cooked) input — but Ink's `beginSuspend()` TURNED OFF raw mode
      // ("Hand input back to the terminal (raw mode off...)", ink.js), so we
      // have to turn it back ON, on OUR OWN, fresh stream.
      relayStdin.setRawMode(true)
      relayStdin.on('data', (chunk) => {
        // The child's `write()` ALSO accepts a Buffer (`Buffer.from(data)` in
        // node-pty's CustomWriteStream, no string branch) — we pass the raw
        // bytes through UNCHANGED, without a decode/encode detour, so that a
        // multi-byte character can NEVER break at a chunk boundary.
        try { child.write(chunk) } catch { /* the child is already gone — the byte is lost, that's legitimate */ }
      })

      // (BONUS) TRACKING THE TERMINAL SIZE: on the `script`-based path hunk
      // is locked to the size it got AT THE MOMENT OF SPAWN, until `q`
      // (a known limitation, see `ptyWrap`'s header) — node-pty's `resize()`
      // LIFTS this, if the real terminal is resized WHILE hunk IS RUNNING.
      process.stdout.on('resize', resizeHandler)

      child.onExit(({ exitCode, signal }) => {
        watchdogShim.exitCode = exitCode
        watchdogShim.signalCode = signal ?? null
        // `flush()` DELIBERATELY discards, rather than writing out, whatever
        // character tail is left over at the END OF THE STREAM, still not
        // decidable — a truncated escape prefix (the child died IN THE
        // MIDDLE, before closing it) would be worse on the terminal than its
        // absence. See `createAltScreenExitFilter.flush`'s header.
        filter.flush()
        // (COSMETIC, see `openReviewView`'s `exit` hook's reasoning): the
        // caller can step back into the alt screen on this as early as
        // possible — although THEORETICALLY, because of the filtering above,
        // we already never leave it, this call is a SAFEGUARD in case the
        // filter ever slips past a DIFFERENTLY formatted escape from some
        // future hunk version.
        try { onExit?.() } catch { /* cosmetic hook: its error must not fail closing the view */ }
        done(resolve)
      })
    } catch (error) {
      // THE SYNCHRONOUS WIRING failed (e.g. stdin CAN'T be put into raw
      // mode) — the child is ALREADY running by this point, so we must NOT
      // leave it orphaned for the caller: the same doctrine as on the
      // `script`-based path (`finally` always closes).
      try { child.kill('SIGKILL') } catch { /* already gone / never started */ }
      reject(error)
    }
  })
}

/**
 * SWITCHING the EXISTING hunk session over to the selected PR's diff.
 *
 * The user's request: "couldn't the TUI maintain its own singleton hunk
 * session?" — WITHIN the LIMITS of hunk's API, this is the most that's
 * achievable:
 *
 *   - OPENING a session can only be done by `hunk diff` / `hunk show`, and it
 *     starts an INTERACTIVE TUI (MEASURED: there's no `--headless` /
 *     `--detach` / `--background` in `hunk diff --help`'s option list). So
 *     the TUI can't open a session "quietly" in the background.
 *   - The `hunk session *` subcommands ONLY control an EXISTING session.
 *   - `hunk session reload --repo <path> -- diff <ref>`, though, SWAPS OUT
 *     the active session's content — so ONCE there's a session, switching PR
 *     doesn't need a new one. THIS is the core of the singleton behavior.
 *
 * The `--` separator is load-bearing: after it, hunk reads the rest as an
 * EMBEDDED command (`diff <range>`), not as `session reload`'s own flag.
 */
export function hunkSessionReloadCommand(repoRoot, base, head) {
  return ['session', 'reload', '--repo', repoRoot, '--', 'diff', `${base}...${head}`]
}

/**
 * Is the hunk session ALIVE? THREE STATES, deliberately — a boolean would
 * lie here.
 *
 *   `true`  — there's an active session (exit 0).
 *   `false` — there ISN'T, but this is NOT AN ERROR: open one. This also
 *             covers the ORPHANED SESSION case, which is exactly what the
 *             user ran into: the registered session's repo root was an
 *             ALREADY DELETED temp directory
 *             (`/private/var/…/tmp.G4I6zLIvk5/probe`), and for the mobile
 *             repo there was NO session at all. The TUI has to treat this AS
 *             IF THERE WERE NONE — open a new one, don't throw an error.
 *   `null`  — NOT KNOWABLE. On a NAMED other error (daemon crash, locked DB,
 *             permissions) or a MISSING BINARY (ENOENT), "no session" would
 *             be a FALSE DIAGNOSIS, which would start a SECOND hunk for the
 *             same underlying problem. The caller gets the RAW error in
 *             this case.
 *
 * THE DETECTION rests on the same two signals as `isNoActiveSession` (hunk's
 * text can change across versions, so it's not a literal match) — but here
 * the third state is also named, because session affinity builds a DECISION
 * on it.
 */
export function hunkSessionAlive(res) {
  if (!res) return null
  // THE MISSING BINARY COMES FIRST, before the status check: on ENOENT
  // `status` is null, from which the silent branch below would make "no
  // session" — DISHONEST, because we know nothing about the session's state
  // (see hunkComments's ENOENT branch).
  if (res.error) return null
  if (res.status === 0) return true
  const stderr = String(res.stderr ?? '').trim()
  const stdout = String(res.stdout ?? '').trim()
  if (NO_ACTIVE_SESSION_RE.test(stderr)) return false
  // THE SILENT non-zero exit: no readable session state → fail-soft "none".
  if (stderr === '' && stdout === '') return false
  // A NAMED OTHER error: we don't guess.
  return null
}


/**
 * The argv for the `hunk session comment list` call — for AGENT-written
 * findings.
 *
 * `--type agent` is NOT a style choice, it's a MEASUREMENT. On hunk 0.17.0,
 * for the SAME ONE, CLI-written comment, the five filters gave:
 *   --type live -> 1 | --type all -> 3 | --type user -> 0 | --type ai -> 0 (!) | --type agent -> 1
 * So a comment written via the CLI (`comment add` / `comment apply`) has
 * `source: "agent"`, NOT `"ai"` — `--type ai` ALWAYS gives an empty list. If
 * the upload were built on that, it would SILENTLY upload nothing: the
 * developer would think they'd sent the findings, while in fact an empty
 * review (or nothing) went out.
 *
 * Why not the unfiltered ("live") path: that's the LEGACY view, which gives
 * the (a) schema (filePath/side/line/summary). In the agent-driven flow,
 * `--type agent` is the semantically correct filter (we need the AGENT's
 * findings, not the legacy live view), and it gives the (b) schema — see
 * parseHunkAgentComments.
 */
export function hunkCommentsCommand(repoRoot) {
  return ['session', 'comment', 'list', '--repo', repoRoot, '--type', 'agent', '--json']
}

/**
 * Parsing `comment list --type agent --json`'s (b) SCHEMA into the internal
 * (filePath/side/line/summary) shape that toGithubComments expects.
 *
 * THE TWO SCHEMAS (measured, hunk 0.17.0, the SAME comment):
 *   (a) `comment list --json` (unfiltered, "live"):
 *       {commentId, filePath, hunkIndex, side, line, summary, rationale, createdAt}
 *   (b) `comment list --type agent|all --json`:
 *       {noteId, source, filePath, hunkIndex, newRange|oldRange, body, createdAt, editable}
 *
 * (b) has NO `line` and NO `side`:
 *   - the line position is `newRange[0]` / `oldRange[0]`,
 *   - the SIDE is determined by WHICH of `newRange` / `oldRange` is PRESENT,
 *   - `body` is the concatenated summary + "\n\n" + rationale (hunk joins
 *     them).
 * So on the (b) schema `c.line` is `undefined` — on the naive path this
 * would have SILENTLY degraded the finding to a `subject_type:"file"`
 * file-level comment: the finding gets posted, but NOT where the agent
 * pointed.
 *
 * FAIL-CLOSED, at three points. A slipped line position is a review comment
 * put in the wrong place, which is worse than a loud failure:
 *   1. unparseable output → throw, with the RAW output;
 *   2. missing `comments` key → throw (a silent empty list would claim "no
 *      findings", when actually the CONTRACT failed);
 *   3. a finding with no position (neither oldRange nor newRange) → throw.
 * An EMPTY `comments`, though, is LEGITIMATE: the user filtered everything
 * out in hunk (`comment rm`) — that must not be treated as an error.
 */
export function parseHunkAgentComments(stdout) {
  const raw = String(stdout ?? '')
  const clip = (s) => (s.length > 2000 ? `${s.slice(0, 2000)}…[truncated]` : s)
  let env
  try {
    env = JSON.parse(raw)
  } catch {
    throw new Error(
      '`hunk session comment list --type agent --json`\'s output is not parseable JSON '
      + '— NOT uploading anything.\n'
      + `raw output:\n${clip(raw.trim()) || '(empty)'}`,
    )
  }
  if (!env || !Array.isArray(env.comments)) {
    throw new Error(
      'hunk\'s output has NO `comments` array — the contract failed, so we are NOT '
      + 'uploading anything (an empty list here would be a dishonest "no findings").\n'
      + `raw output:\n${clip(raw.trim()) || '(empty)'}`,
    )
  }
  return env.comments.map((c, i) => {
    const where = c?.filePath ? `${c.filePath} (${c?.noteId ?? `#${i}`})` : `finding #${i}`
    // The position is the ONE field that can't be guessed: newRange and
    // oldRange live in DIFFERENT coordinate spaces (post- vs. pre-image), so
    // their absence lets us infer neither.
    const newLine = Array.isArray(c?.newRange) ? c.newRange[0] : undefined
    const oldLine = Array.isArray(c?.oldRange) ? c.oldRange[0] : undefined
    if (!Number.isInteger(newLine) && !Number.isInteger(oldLine)) {
      throw new Error(
        `${where}: the finding is missing a position (neither \`newRange\` nor \`oldRange\`) — `
        + 'the line position CANNOT be guessed, a slipped line would mean a review comment '
        + 'placed in the wrong spot. NOT uploading anything.\n'
        + `raw finding:\n${clip(JSON.stringify(c))}`,
      )
    }
    const body = typeof c?.body === 'string' ? c.body : ''
    if (body.length === 0) {
      throw new Error(
        `${where}: the finding's \`body\` is empty — not uploading an empty GitHub comment.\n`
        + `raw finding:\n${clip(JSON.stringify(c))}`,
      )
    }
    // The FULL body goes into the `summary` field, WITHOUT `rationale`: hunk
    // has already concatenated the two in the (b) schema, so a separate
    // re-joining of rationale in toGithubComments would duplicate the text.
    return {
      noteId: c.noteId,
      source: c.source,
      filePath: c.filePath,
      side: Number.isInteger(newLine) ? 'new' : 'old',
      line: Number.isInteger(newLine) ? newLine : oldLine,
      summary: body,
    }
  })
}

// --- "NO ACTIVE HUNK SESSION": a separate error class -----------------------
//
// A REAL, USER-REPORTED BUG (#904, `r` = AI review). hunk gave this:
//   exit 1 · stderr: "hunk: No active session matches repoRoot /…/<repo>"
//   stdout: (empty)
// and the TUI printed this raw:
//   AI review error: hunk comment list (exit 1): hunk: No active session …
// The FAIL-CLOSED behavior is CORRECT (the `before` measurement is BEFORE
// the claude call, so the failure did NOT spend a token), but the MESSAGE
// was useless: it didn't say WHAT the user should do. The AI review flow has
// the agent write findings INTO THE HUNK SESSION (hunk-review skill,
// `comment apply`), so an ACTIVE SESSION is the PRECONDITION — this has to
// be stated, together with how to open one.

/**
 * The path for opening a hunk session — in ONE place, so the error message
 * and the confirmation screen don't drift apart (duplicated user-facing text
 * is exactly the error class this module avoids elsewhere too).
 */
export const HUNK_SESSION_HINT =
  'open one: from the TUI, `d` (diff-review) starts it with the PR\'s diff, or in a '
  + 'separate terminal `hunk diff <base>...<head>`'

/**
 * Does hunk's output recognize the "no active session" state?
 *
 * The detection rests on TWO SIGNALS, not one exact string — hunk's message
 * can change across versions, and a literal match would silently fall back
 * to the old, useless message:
 *   (1) stderr contains the `No active session` substring, OR
 *   (2) non-zero exit + EMPTY stdout — there's no readable session state
 *       there either.
 *
 * FAIL-CLOSED IN THE OTHER DIRECTION TOO: if stderr names some OTHER,
 * specific error (daemon crash, locked DB, permissions), signal (2) is NOT
 * enough — better a raw error than a FALSE diagnosis that sends the user
 * looking for a session over an install/daemon problem.
 */
/**
 * The "there is no live session" wording, tolerantly.
 *
 * MEASURED, AND THIS WAS A REAL BUG: the pattern used to be the exact phrase
 * `no active session`, and hunk 0.17.0 actually says
 *
 *   "No active Hunk sessions are registered with the daemon."
 *
 * — a word inserted in the middle and a plural, so the match failed. The
 * consequence was not a wrong message but a WRONG BRANCH: the caller could no
 * longer tell "no session yet" from "something is broken", stopped falling
 * back to opening one, and the very first `d` on a clean machine died instead
 * of showing the diff. The code's own comment claimed it deliberately avoided
 * matching an exact string; it did not, and only running it revealed that.
 *
 * The shape is therefore anchored on what the sentence MEANS — an absence of
 * an active session — and stays indifferent to the words hunk puts between,
 * and to singular versus plural.
 */
const NO_ACTIVE_SESSION_RE = /\bno active\b[^.]*\bsessions?\b/i

export function isNoActiveSession(res) {
  if (!res || res.status === 0) return false
  const stderr = String(res.stderr ?? '').trim()
  const stdout = String(res.stdout ?? '').trim()
  if (NO_ACTIVE_SESSION_RE.test(stderr)) return true
  // Signal (2) ONLY decides if hunk said nothing at all — alongside a NAMED
  // other error, "no session" would be a guess.
  return stderr === '' && stdout === ''
}

/**
 * The "no active session" message — TAILORED TO THE CALL CONTEXT.
 *
 * The two contexts mean DIFFERENT things for the same state, hence not one
 * text:
 *  - `review`: the AI review WRITES findings INTO the session, so an active
 *    session is the PRECONDITION → open one. Plus the reassuring, TRUE
 *    statement: the failure happens BEFORE the claude call, so NO tokens
 *    were spent.
 *  - `upload`: the `f` path READS FROM the session, so "no session" simply
 *    means THERE'S NOTHING TO UPLOAD — there, the "open a session" call to
 *    action would be misleading (the problem isn't the missing session, it's
 *    the findings). THIS MESSAGE ONLY REACHES the user AS A LAST RESORT: the
 *    caller (`doUpload`) FIRST falls back to the cached review findings on
 *    the "no session" class, and this text only goes out if THAT was also
 *    empty — so the "NOTHING TO UPLOAD" claim is true. Without the fallback
 *    it was FALSE: in the user's #904 case two findings sat in the cache,
 *    while this message claimed the opposite.
 *  - `after`: the measurement AFTER the AI review. claude has ALREADY RUN,
 *    so the "we spent no tokens" sentence would be a LIE here — the session
 *    closed WHILE it ran, and the findings were lost.
 */
export function noActiveSessionMessage(repoRoot, context = 'review') {
  if (context === 'upload') {
    return `no active hunk session for this repo (${repoRoot}), so there's nothing to upload. `
      + 'Findings live in the hunk session; if there\'s anything to upload, first '
      + `${HUNK_SESSION_HINT}.`
  }
  if (context === 'after') {
    return `the hunk session ended DURING the review (${repoRoot}), so the findings `
      + 'can\'t be read back — the review has ALREADY RUN, meaning the cost was already spent. '
      + `Start a new session (${HUNK_SESSION_HINT}), and re-run the AI review.`
  }
  return `no active hunk session for this repo (${repoRoot}). `
    + 'The AI review writes findings into the hunk session, so an active session is the PRECONDITION — '
    + `${HUNK_SESSION_HINT}. `
    + 'No tokens were spent: the failure happens BEFORE the claude call.'
}

/**
 * The agent findings REMAINING in the hunk session (the user has already
 * filtered with `comment rm`).
 *
 * On a hunk error it gives EXIT=1 + plain text stderr, with no structured
 * error object — so WE check the exit status ourselves, without swallowing
 * it.
 *
 * `context` picks the ERROR TEXT (`review` | `upload`) — see
 * noActiveSessionMessage.
 */
export function hunkComments(repoRoot, { context = 'review' } = {}) {
  const res = spawnSync(hunkBin(), hunkCommentsCommand(repoRoot), { encoding: 'utf8' })
  // THE NOT-INSTALLED binary comes BEFORE the status check. A MEASURED false
  // diagnosis: on ENOENT spawnSync gives `status: null`, from which the
  // branch below would make "exit null: no active session" — DISHONEST,
  // because we know nothing about the session's state, only that the binary
  // is missing. The developer would have gone looking in the hunk session
  // for an installation error.
  if (res.error?.code === 'ENOENT') {
    throw new Error(
      'the `hunk` binary is not launchable — neither core\'s bundled instance '
      + '(`node_modules/.bin/hunk`, the `hunkdiff` dependency), nor one on PATH. '
      + 'Run `pnpm install` in core. That\'s why the review comments '
      + 'can\'t be read. This is NOT a session error: the binary itself is missing.\n'
      + 'What to do: `brew install hunk` (installs it/puts it on PATH), then try again.',
    )
  }
  if (res.error) throw new Error(`hunk didn't start: ${res.error.message}`)
  if (res.status !== 0) {
    // "No active session" is a SEPARATE error class: an actionable message,
    // WITHOUT the raw `comment list (exit N)` form.
    if (isNoActiveSession(res)) throw new Error(noActiveSessionMessage(repoRoot, context))
    // EVERY OTHER hunk error falls back to the RAW message: a false
    // diagnosis is worse than the raw stderr.
    throw new Error(
      `hunk comment list (exit ${res.status}): ${(res.stderr || '').trim() || '(no stderr)'}\n`
      + `stdout: ${(res.stdout || '').trim() || '(empty)'}`,
    )
  }
  return parseHunkAgentComments(res.stdout)
}

/** The count of agent findings IN the hunk session — the aiReviewGate's measurement. */
export function hunkCommentCount(repoRoot, opts) {
  return hunkComments(repoRoot, opts).length
}

/**
 * Uploading the findings as ONE GitHub review (event=COMMENT).
 * The `--input -` path is needed: the comments[] object array can't be
 * assembled with the -f/-F field flags. --method POST is explicit, because
 * with --input the default method stays GET.
 */
export function uploadFindings(pr, comments, { model, user, ...attribution }) {
  const payload = JSON.stringify({
    event: 'COMMENT',
    // The attribution (tool / aiGenerated / costUsd / sessionId) PASSES
    // THROUGH: in an AI-generated finding's body, provenance isn't optional.
    body: reviewBody({ ...attribution, model, user, count: comments.length }),
    comments: toGithubComments(comments),
  })
  const repo = spawnSync('gh', ['repo', 'view', '--json', 'nameWithOwner', '--jq', '.nameWithOwner'], { encoding: 'utf8' })
  // The repo name must NOT be silently swallowed either: with an empty nwo,
  // the `gh api repos//pulls/N/reviews` path would give a 404, and the error
  // message would obscure the real cause (auth / not a repo cwd).
  const repoSpawnErr = spawnFailure(repo, 'gh')
  if (repoSpawnErr) throw new Error(`the repo name can't be queried: ${repoSpawnErr}`)
  if (repo.status !== 0) {
    throw new Error(`the repo name can't be queried: ${(repo.stderr || '').trim() || `gh exit ${repo.status}`}`)
  }
  const nwo = repo.stdout.trim()
  if (!nwo) throw new Error('the repo name came back empty from gh — the upload target can\'t be guessed')
  const res = spawnSync('gh', ['api', `repos/${nwo}/pulls/${pr}/reviews`, '--method', 'POST', '--input', '-'], {
    input: payload,
    encoding: 'utf8',
  })
  // THE SPAWN ERROR COMES FIRST: on ENOENT `res.stderr` is UNDEFINED, so the
  // `res.stderr.trim()` below would itself have thrown a TypeError — the
  // user would have gotten a "Cannot read properties of undefined" line
  // instead of the real cause.
  const postSpawnErr = spawnFailure(res, 'gh')
  if (postSpawnErr) throw new Error(`the review upload can't be started: ${postSpawnErr}`)
  if (res.status !== 0) {
    // BOTH STDERR AND STDOUT ARE NEEDED, AND THIS IS A MEASURED FINDING (the
    // user's #904 422): `gh api` writes the HTTP error to stderr in a
    // GENERIC form (`gh: Unprocessable Entity (HTTP 422)`), but GitHub's
    // RESPONSE BODY — where `message` and `errors[]` name the FAULTY
    // COMMENT and its field — goes to STDOUT. The old code preferred stderr
    // (`||`), so the user got exactly the sentence that reveals NOTHING:
    // they had no way to know WHICH finding, WHICH field of it, failed the
    // WHOLE (atomic) review.
    //
    // 422 GETS A SEPARATE EXPLANATION: it's the most common outcome on this
    // path, and its three typical causes (`line` isn't in the diff hunk /
    // wrong `side` / bad `path`) all trace back to the COMMENT POSITION. The
    // raw body is there regardless, but spelling out the diagnosis direction
    // saves hours.
    const out = (res.stdout || '').trim()
    const err = (res.stderr || '').trim()
    const detail = [err, out].filter((s) => s !== '').join('\n') || '(no output)'
    const hint = /\b422\b|Unprocessable/i.test(`${err}\n${out}`)
      ? '\nOn this path a 422 is almost always a COMMENT POSITION issue: `line` isn\'t '
        + 'within the PR\'s diff hunks, `side` (RIGHT/LEFT) doesn\'t match the measured '
        + 'coordinate space, or `path` isn\'t relative to the repo root. `comments[]` is '
        + 'ATOMIC: a single bad position fails the WHOLE review.'
      : ''
    throw new Error(`the review upload did not succeed (exit ${res.status}): ${detail}${hint}`)
  }
  return JSON.parse(res.stdout)
}

/**
 * WRITING the AI findings INTO the hunk session — this is the human-in-the-loop
 * gate.
 *
 * Why not straight to GitHub: the review body's `verifiedBy` claim is only
 * true if the developer actually reviewed the findings. The hunk session is
 * the place where they can go through them, delete and edit them — and
 * afterward the EXISTING 'f' path (hunkComments → toGithubComments →
 * uploadFindings) uploads them, unchanged.
 *
 * `--author` is the provenance: in the hunk session too, it shows which
 * comment the AI generated and which the developer wrote.
 */
export function injectHunkComments(repoRoot, findings, { author = 'claude-p' } = {}) {
  let added = 0
  for (const f of findings) {
    const args = [
      'session', 'comment', 'add',
      '--repo', repoRoot,
      '--file', f.filePath,
      '--summary', f.summary,
      '--author', author,
    ]
    if (f.line !== undefined && f.line !== null) {
      args.push(f.side === 'old' ? '--old-line' : '--new-line', String(f.line))
    }
    if (f.rationale) args.push('--rationale', f.rationale)
    const res = spawnSync(hunkBin(), args, { encoding: 'utf8' })
    // A MISSING BINARY is a separate diagnosis (see hunkComments's ENOENT
    // branch): "hunk exit null" would suggest that the write failed, when
    // actually hunk never even started — the developer would have gone
    // debugging the session.
    const spawnErr = spawnFailure(res, 'hunk')
    if (spawnErr) {
      throw new Error(
        `writing finding #${added + 1} can't be started (${f.filePath}:${f.line}): ${spawnErr} `
        + `${added} finding(s) already got in — in hunk you'll see ONLY those.`,
      )
    }
    // Fail-closed: after a failed write we do NOT silently continue, because
    // the developer would think they're seeing every finding in hunk — and
    // wouldn't know the missing one is missing. We report the count already
    // written.
    if (res.status !== 0) {
      // "No active session" is a SEPARATE error class here too (the same
      // detector): `comment add` needs a session just like `comment list`
      // does, and the raw hunk stderr wouldn't tell the developer what to do
      // either.
      if (isNoActiveSession(res)) {
        throw new Error(
          `${noActiveSessionMessage(repoRoot, 'review')} `
          + `(failed while writing finding #${added + 1}: ${f.filePath}:${f.line}; `
          + `${added} finding(s) got in.)`,
        )
      }
      throw new Error(
        `writing finding #${added + 1} into the hunk session did not succeed (${f.filePath}:${f.line}): `
        + `${(res.stderr || res.stdout || '').trim() || `hunk exit ${res.status}`}. `
        + `${added} finding(s) already got in — in hunk you'll see ONLY those.`,
      )
    }
    added += 1
  }
  return added
}
